number: 9
title: Chunk and Word Counts by Chapter in the Silmarillion
description: |
  chunks are paragraph-like units (including poetry stanzas) and words are tokenized by first converting em-dashes to whitespace then splitting on whitespace.
tags: [tolkien, silmarillion, digitalhumanities]
