number: 8
title: Chunk and Word Counts by Book in Lord of the Rings (Scatter Plot)
description: |
  Intriguing how much the two halves cluster the way they do.
tags: [tolkien, lotr, lordoftherings, digitalhumanities]
